# Generated by Django 2.2.13 on 2020-06-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200627_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
